Move AddItem view into List view and Style AddItem component
the-collab-lab/tcl-47-smart-shopping-list pull request #40
Opened 2022-11-21 23:51 UTC by wheninseattle

## Description

This feature branch moves the AddItem view into the List view and creates an AddItem button which toggles the component's visibility within the List view. Additionally, this branch makes some minor style updates to the MUI theme, and replaces existing input, radio, typography, and button tags in the AddItem component with their corresponding MUI components.
Finally, this branch refactors the navbar and router to remove AddItem as a view/page.

## Related Issue

closes #36 
closes #32 

## Acceptance Criteria

#### Issue 19
- [ ]  Import Add Item component into List.jsx
- [ ]  Style component to match wireframe at: https://www.figma.com/file/N8D1ermyhj04g2X9WAxhjc/TCL-47-Honeydew?node-id=0%3A1
#### Issue 16

1. [ ] Move AddItem component from `src/views` to `src/components` and remove the component export from `src/views/index.js`. You will also need to remove the route from `App.jsx`.

- [ ] Nest AddItem component _above_ rendered list items 
- [ ] Add an 'AddItem' button to toggle the rendering of AddItem
- [ ] The 'filter items' input should toggle off when the AddItem component is rendered. This will cut down on clutter and may help users maintain their focus on the proper input.

### A Stretch Goal
- [ ] Find a way to 'stick' the toggle button to the bottom of the app window, so its location is consistent. Alternatively, place the button at the top of the list so users don't have to travel far between the toggle button and add list functionality. Your choice!

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|  ✓  | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

<img width="658" alt="AddItemView" src="https://user-images.githubusercontent.com/49693755/203177452-6dde7c31-95f5-4795-90ba-a679625793f5.png">

### After

<img width="658" alt="NestedAddItem" src="https://user-images.githubusercontent.com/49693755/203177486-985d2acd-402f-4add-8bbd-c3cd15192623.png">

## Testing Steps / QA Criteria

1.  Use `git pull WN-Nest-AddItem` to pull feature branch.
2. Run `npm start` to launch live server and navigate to localhost:3000/list in your browser
3. Ensure that the '+' Add Item button is rendered next to search field.
4. Click and ensure that it toggles the AddItem component.
5. Ensure functionality of AddItem component
6. Use `localstorage.clear()` to remove list token, and return to localhost:3000/list to ensure that the page is behaving as expected for the edge cases of A) No token present and B) A list with no list items

2022-11-22 01:08 UTC, a-cole55 reviewed
Great job Weston! The app is coming together so well already. I love having the AddItem component on the List view. Amazing touch! Also, thank you for tackling the edge cases of having a token but not being able to access the home page, etc.

One small nit, can the filtered items component/search bar be extended out just a tab bit further? I'm thinking about halfway between the "Apples" in "5 Cosmic Apples" and the badges?

2022-11-22 03:37 UTC, wheninseattle commented
Thanks for the feedback, @a-cole55. Oh yeah, great call on the SearchBar width. I just made that fix; hopefully that feels better.

2022-11-22 05:07 UTC, tmflower approved these changes
Nice job, Weston! It looks and works great. I'm really glad I spent some time learning about MUI today; otherwise I would have been totally lost looking at this! I did have to look up what a Fab is though...that didn't come up earlier. I must say with a name like Fab, I expected it to be 🍾🥳💃🎇 But I guess a button is cool too. 😂

Great work!

2022-11-22 05:46 UTC, mariahschock approved these changes
This looks and functions fantastically! Thank you for tackling this ticket, Weston!

2022-11-22 13:16 UTC, a-cole55 approved these changes
Nice! Great job again Weston! I love the attention to detail.

2022-11-22 17:01 UTC, wheninseattle commented
@tmflower It _does_ seem like 'FAB' should have been reserved for something a little more fabulous!

2022-11-25 22:13 UTC, YolandaHaynes commented
I really like how this app is coming along! Love the paper look for styling.  I really like the new feature of the add button inside the list section, so I'm not toggling between the two pages 😄.
However, I did notice that when I add items for "not soon", the item ends up in "kind of soon" section.

2022-11-25 22:13 UTC, YolandaHaynes requested changes

2022-11-25 22:13 UTC, YolandaHaynes commented on src/views/List.jsx
> +							<br />
Haven't seen a ```<br >``` in a while. If you have the time and bandwidth, definitely try to find alternative way to style it. I believe  ```<br >``` aren't semantically appropriate. But I have heard some debate about it.

2022-11-25 22:14 UTC, YolandaHaynes requested changes
I really like how this app is coming along! Love the paper look for styling. I really like the new feature of the add button inside the list section, so I'm not toggling between the two pages 😄.
However, I did notice that when I add items for "not soon", the item ends up in "kind of soon" section.

2022-11-25 23:58 UTC, tmflower commented
Good catch, Yolanda! I must admit I did not verify adding items to each
category. Which made me go back and try it on the current main branch, and
the same thing happened there. So I'm thinking that this bug originates
from a previous commit (one of the ones where we were working with the
sorting function).

On Fri, Nov 25, 2022 at 12:14 PM Yolanda Haynes ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> I really like how this app is coming along! Love the paper look for
> styling. I really like the new feature of the add button inside the list
> section, so I'm not toggling between the two pages 😄.
> However, I did notice that when I add items for "not soon", the item ends
> up in "kind of soon" section.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/the-collab-lab/tcl-47-smart-shopping-list/pull/40#pullrequestreview-1194786055>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWNV47MXF3LTM5ZSZSDAMADWKE257ANCNFSM6AAAAAASHFXPQY>
> .
> You are receiving this because you were mentioned.Message ID:
> <the-collab-lab/tcl-47-smart-shopping-list/pull/40/review/1194786055@
> github.com>
>

2022-11-26 01:57 UTC, wheninseattle commented
@YolandaHaynes Great call on the `<br/>` 😂
And thank you for flagging that bug. @tmflower, I really appreciate you looking into it. I will make the change as suggested. So, will new 'not soon' items only appear as 'not soon' for one day? If that is the case, it seems like the only way items end up 'not soon' is if there is a pattern of the user waiting over a month between each purchase and the app 'learns' that it has should be 'not soon'

2022-11-26 08:02 UTC, YolandaHaynes approved these changes
Awesome find and great catch @tmflower!  It's always interesting when dealing with numbers. 
@wheninseattle thanks for making the changes. Just be sure to update those comments, if you are going to keep it in there, to reflect the new code changes. As for 'not soon' for one day...I'm not sure. Since it is infrequent, it will probably take a bit for the app to 'learn'.

2022-11-26 14:53 UTC, merged